[package]
name = "rust"
version = "0.2.0"
authors = [
    "Michael Gerhaeuser <michael.gerhaeuser@gmail.com>",
    "rrokkam <rohithrokkam@gmail.com>",
    "Jean-Sébastien Dominique <jd@amateurradio.engineer>",
]
edition = "2024"
